C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#48305c" -opaque "#af00bf" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#805090" -opaque "#c700d9" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#9966cc" -opaque "#e800ff" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#c880ff" -opaque "#e878ff" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#dcb4ff" -opaque "#ffb4ff" "%~f1"

C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#48305cAF" -opaque "#af00bfAF" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#805090AF" -opaque "#c700d9AF" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#9966ccAF" -opaque "#e800ffAF" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#c880ffAF" -opaque "#e878ffAF" "%~f1"
C:\Users\Nick\Desktop\imagick\convert.exe "%~f1" -fill "#dcb4ffAF" -opaque "#ffb4ffAF" "%~f1"